[package]
name = "gen"
version = "0.1.0"
authors = ["kyasu1 <kyasuyako@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
svg = "0.8"
Inflector = "0.11"
glob = "0.3"
base64 = "0.12"
